[package]
name = "Switchboard"
version = "0.0.0"

[addresses]
Std = '0x1'
AptosFramework = '0x1'
Switchboard = '0x28D1992CE2FBD74C539CC58337DC678F72FC656DD41AAD534FB0BC8C01EAF552'

[dev-addresses]
Switchboard = '0x3'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework/"
rev = "908aff867fcc1e1b12f058d474329097ab96f14b"